require_relative 'lib-ui-test'

open()

login("test_admin", "password")
toStudentsAdminTab()
p findTableItemByContent("tableData", "test_student")
toTeachersAdminTab()
p findTableItemByContent("tableData", "test_teacher") 
toClassroomsAdminTab()
toProfile()
navBarHome()
clickProfDisplay()
logout()

login("test_teacher", "password")
selectClassroom("test_class")
toAssignmentsTab()
toGradesTab()
toAttendanceTab()
toStudentsTab()
toProfile()
navBarHome()
clickProfDisplay()
editPassword("password", "password!")
logout()
login("test_teacher", "password!")
toProfile()
editPassword("password!", "password")
logout()

login("test_student", "password")
selectClassroom("test_class")
toAssignmentsTab()
toGradesTab()
toAttendanceTab()
toProfile()
navBarHome()
clickProfDisplay()
logout()

close()