ruby -W0 navigation-ui-test.rb
ruby -W0 dashboard-ui-test.rb
ruby -W0 classroom-ui-test.rb
ruby -W0 profile-ui-test.rb
ruby -W0 assignments-ui-test.rb
ruby -W0 attendance-ui-test.rb
ruby -W0 grades-ui-test.rb
ruby -W0 students-ui-test.rb
ruby -W0 file-submission-ui-test.rb